### ISSUE TITLE
README's problem

### ISSUE THREAD

**Issue by tleb** [niklongstone/Fakerino#10]
`Fake 500,000 data in 1 minute.` is simply not possible in a lib description. On what hardware? On what software? What data?

Numbers like this are good to:
1. Compare two or more libs (if results were given for multiple libs, which is not the case).
2. Attract ~~ignorant~~ ~~weird~~ special people.

Sadly, I am not sure that's the way to go to have an attractive lib. (I am an example, I haven't looked at the code but I already have a negative view of the lib.)

**Comment by niklongstone** [comment]
Thanks for the feedback @tleb, 
I agree, that declaration needs more specifications.

Actually, there was a plan to provide benchmarks in the documentation.

I will change the README till the benchamark won't be ready.

If you want to try someting very easy, the snippet below takes around 45 sec on a 
MacBook Pro, 2.2 GHz Intel Core i7, 16 GB 1333 MHz DDR3 with PHP 5.5.27(cli)

```
<?php
require 'vendor/autoload.php';
use Fakerino\Fakerino;

$fakerino = Fakerino::create();
$numberOfTimes = 500000;
$data = '';

$before = microtime(true);
for ($i=0 ; $i < $numberOfTimes ; $i++) {
    $data .=$fakerino->fake('surname');
}
echo $data;
$after = microtime(true);

echo $after-$before . " sec\n";
```
